replicaCount: 1

image:
  repository: ghcr.io/plan-eo/dashboard
  tag: prod-1.0.2
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 4000

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: "500m"
    memory: 1Gi

pvc:
  claimName: plan-eo-data-pvc